kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: poc
  labels:
    type: local
    app: poc-medium-fastapi-deployment
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/kind/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-control-plane  # <-- name of the node (docker-desktop, minikube) etc.