apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: poc
  labels:
    app: poc-medium-fastapi-deployment
data:
  POSTGRES_DB: "cG9j" # poc
  POSTGRES_USER: "cG9zdGdyZXM=" # postgres
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # postgres