apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-medium-fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-medium-fastapi-deployment
  template:
    metadata:
      labels:
        app: poc-medium-fastapi-deployment
    spec:
      containers:
      - name: poc-medium-fastapi
        image: alorencatto/poc-medium-fastapi-kubernetes:latest # TODO : Mudar aqui
        command: ["uvicorn","src.infrastructure.http.app:app","--host","0.0.0.0","--port","8000","--reload"]
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            port: 8000
            path: /docs
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            port: 8000
            path: /docs
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: secret-poc-medium-fastapi-deployment
                key: DATABASE_URL