apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-poc-medium-fastapi-deployment
spec:
  selector:
    app: poc-medium-fastapi-deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31553
  type: NodePort